### ISSUE TITLE
Scope der main.py festlegen

### ISSUE THREAD

**Issue by Dasanyx** [JESchoett/Turnierplaner#1]
Es gibt die Möglichkeit den Top-Level Scope in Python festzulegen.

`if __name__ == "__main__":`

Hilft festzulegen was in welcher Reihenfolge abläuft.
kurze Erklärung:
https://realpython.com/python-main-function/
längere Erklärung:
https://realpython.com/if-name-main-python/
offizielle Doku:
https://docs.python.org/3/library/__main__.html

**Comment by JESchoett** [comment]
Guter Punkt!
Ich habe die Funktionen strukturiert und die Main Methode angelegt.
Danke dir.
